name: mrzorro_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  local_auth: ^2.1.7
  image_picker: ^1.0.7
  http: ^1.1.0
  intl: ^0.19.0
  path_provider: ^2.1.1


flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700